var gdprConfigurationOptions = { complianceType: 'opt-in',
	cookieConsentLifetime: 365,
	cookieConsentSamesitePolicy: 'Strict',
	cookieConsentSecure: 1,
	disableFirstReload: 1,
	  blockJoomlaSessionCookie: 0,
	blockExternalCookiesDomains: 1,
	externalAdvancedBlockingModeCustomAttribute: '',
	allowedCookies: '',
	blockCookieDefine: 1,
	autoAcceptOnNextPage: 0,
	revokable: 1,
	lawByCountry: 0,
	checkboxLawByCountry: 0,
	blockPrivacyPolicy: 0,
	cacheGeolocationCountry: 0,
	countryAcceptReloadTimeout: 1000,
	usaCCPARegions: null,
	countryEnableReload: 0,
	customHasLawCountries: [""],
	dismissOnScroll: 0,
	dismissOnTimeout: 0,
	containerSelector: 'body',
	hideOnMobileDevices: 0,
	autoFloatingOnMobile: 0,
	autoFloatingOnMobileThreshold: 1024,
	autoRedirectOnDecline: 0,
	autoRedirectOnDeclineLink: '',
	showReloadMsg: 0,
	showReloadMsgText: 'Applying preferences and reloading the page...',
	defaultClosedToolbar: 0,
	toolbarLayout: 'basic-header',
	toolbarTheme: 'block',
	toolbarButtonsTheme: 'decline_first',
	revocableToolbarTheme: 'basic',
	toolbarPosition: 'bottom-left',
	toolbarCenterTheme: 'compact',
	revokePosition: 'revoke-top',
	toolbarPositionmentType: 1,
	positionCenterSimpleBackdrop: 0,
	positionCenterBlurEffect: 1,
	preventPageScrolling: 0,
	popupEffect: 'fade',
	popupBackground: '#444444',
	popupText: '#ffffff',
	popupLink: '#ffffff',
	buttonBackground: '#555555',
	buttonBorder: '#666666',
	buttonText: '#ffffff',
	highlightOpacity: '100',
	highlightBackground: '#444444',
	highlightBorder: '#666666',
	highlightText: '#ffffff',
	highlightDismissBackground: '#333333',
	  highlightDismissBorder: '#ffffff',
	 highlightDismissText: '#ffffff',
	autocenterRevokableButton: 0,
	hideRevokableButton: 0,
	hideRevokableButtonOnscroll: 0,
	customRevokableButton: 2,
	customRevokableButtonAction: 0,
	headerText: 'Verwendete Cookies',
	messageText: 'Um unsere Website für Sie optimal gestalten und fortlaufend verbessern zu können, verwenden wir Cookies. Weitergehende Informationen finden sie in unserer Cookie-Richtlinie und in unserer Datenschutzerklärung.',
	denyMessageEnabled: 0, 
	denyMessage: 'You have declined cookies, to ensure the best experience on this website please consent the cookie usage.',
	placeholderBlockedResources: 1, 
	placeholderBlockedResourcesAction: 'open',
	  placeholderBlockedResourcesText: '<p>Um diesen Inhalt sehen zu können, müssen sie externen Inhalten zustimmen.<br><span class=\"link\"><i class=\"fas fa-chevron-right\"></i> Hier klicken um die Einstellungen zu ändern.</p>',
	placeholderIndividualBlockedResourcesText: 'You must accept cookies from {domain} and reload the page to view this content',
	placeholderIndividualBlockedResourcesAction: 0,
	placeholderOnpageUnlock: 1,
	scriptsOnpageUnlock: 1,
	dismissText: 'OK',
	allowText: 'Ausgewählte erlauben',
	denyText: 'Ablehnen',
	cookiePolicyLinkText: '<i class=\"fas fa-chevron-right\"></i> Cookie-Richtlinie',
	cookiePolicyLink: './cookie-richtlinie',
	cookiePolicyRevocableTabText: 'Cookie Einstellungen',
	privacyPolicyLinkText: '<i class=\"fas fa-chevron-right\"></i> Datenschutzerklärung',
	privacyPolicyLink: 'datenschutz',
	googleCMPTemplate: 0,
	enableGdprBulkConsent: 0,
	enableCustomScriptExecGeneric: 0,
	customScriptExecGeneric: '',
	categoriesCheckboxTemplate: 'cc-checkboxes-light',
	toggleCookieSettings: 0,
	toggleCookieSettingsLinkedView: 0,
	 toggleCookieSettingsLinkedViewSefLink: '/component/gdpr/',
	  toggleCookieSettingsText: '<span class="cc-cookie-settings-toggle">Einstellungen <span class="cc-cookie-settings-toggler">&#x25EE</span></span>',
	toggleCookieSettingsButtonBackground: '#333333',
	toggleCookieSettingsButtonBorder: '#ffffff',
	toggleCookieSettingsButtonText: '#ffffff',
	showLinks: 1,
	blankLinks: '_blank',
	autoOpenPrivacyPolicy: 0,
	openAlwaysDeclined: 1,
	cookieSettingsLabel: 'Cookie Einstellungen:',
	  cookieSettingsDesc: 'Klicken Sie auf die Checkbox, um Cookies auszuwählen. Klicken Sie auf eine Kategorie um mehr über die verwendeten Cookies zu erfahren.',
	cookieCategory1Enable: 1,
	cookieCategory1Name: 'Notwendig',
	cookieCategory1Locked: 1,
	cookieCategory2Enable: 1,
	cookieCategory2Name: 'Externe Inhalte',
	cookieCategory2Locked: 0,
	cookieCategory3Enable: 1,
	cookieCategory3Name: 'Analytics',
	cookieCategory3Locked: 0,
	cookieCategory4Enable: 0,
	cookieCategory4Name: 'Marketing-Cookies',
	cookieCategory4Locked: 0,
	cookieCategoriesDescriptions: {},
	alwaysReloadAfterCategoriesChange: 1,
	preserveLockedCategories: 1,
	declineButtonBehavior: 'hard',
	reloadOnfirstDeclineall: 0,
	trackExistingCheckboxSelectors: '',
		trackExistingCheckboxConsentLogsFormfields: 'name,email,subject,message',
	allowallShowbutton: 1,
	allowallText: 'Alle Cookies erlauben',
	allowallButtonBackground: '#218838',
	allowallButtonBorder: '#218838',
	allowallButtonText: '#ffffff',
	allowallButtonTimingAjax: 'fast',
	includeAcceptButton: 0,
	trackConsentDate: 0,
	execCustomScriptsOnce: 1,
	optoutIndividualResources: 1,
	blockIndividualResourcesServerside: 0,
	disableSwitchersOptoutCategory: 0,
	allowallIndividualResources: 1,
	blockLocalStorage: 0,
	blockSessionStorage: 0,
	externalAdvancedBlockingModeTags: 'iframe,script,img,source',
	enableCustomScriptExecCategory1: 0,
	customScriptExecCategory1: '',
	enableCustomScriptExecCategory2: 0,
	customScriptExecCategory2: '',
	enableCustomScriptExecCategory3: 0,
	customScriptExecCategory3: '',
	enableCustomScriptExecCategory4: 0,
	customScriptExecCategory4: '',
	enableCustomDeclineScriptExecCategory1: 0,
	customScriptDeclineExecCategory1: '',
	enableCustomDeclineScriptExecCategory2: 0,
	customScriptDeclineExecCategory2: '',
	enableCustomDeclineScriptExecCategory3: 0,
	customScriptDeclineExecCategory3: '',
	enableCustomDeclineScriptExecCategory4: 0,
	customScriptDeclineExecCategory4: '',
	enableCMPStatistics: 0,
	enableCMPAds: 0,
	debugMode: 0
};var gdpr_ajax_livesite='https://www.terras-tiefbau.group/';var gdpr_enable_log_cookie_consent=1;




var gdprUseCookieCategories=1;var gdpr_ajaxendpoint_cookie_category_desc='https://www.terras-tiefbau.group/index.php?option=com_gdpr&task=user.getCookieCategoryDescription&format=raw';

var gdprCookieCategoryDisabled2=1;

var gdprCookieCategoryDisabled3=1;

var gdprCookieCategoryDisabled4=1;

var gdprJSessCook='a86a558f6e167e485e5db0de9e1531ed';var gdprJSessVal='bo381iei4eoddllc70fdk1fcou';var gdprJAdminSessCook='6e79323f0a2913be2b0a62f1d24a44b4';var gdprPropagateCategoriesSession=1;var gdprAlwaysPropagateCategoriesSession=1;var gdprAlwaysCheckCategoriesSession=0;

var gdprFancyboxWidth=700;var gdprFancyboxHeight=800;var gdprCloseText='Schließen';

var gdprUseFancyboxLinks=1;