var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,e,d){a!=Array.prototype&&a!=Object.prototype&&(a[e]=d.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(e){return $jscomp.SYMBOL_PREFIX+(e||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var e=0;return $jscomp.iteratorPrototype(function(){return e<a.length?{done:!1,value:a[e++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.iteratorFromArray=function(a,e){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var d=0,f={next:function(){if(d<a.length){var g=d++;return{value:e(g,a[g]),done:!1}}f.next=function(){return{done:!0,value:void 0}};return f.next()}};f[Symbol.iterator]=function(){return f};return f};
$jscomp.polyfill=function(a,e,d,f){if(e){d=$jscomp.global;a=a.split(".");for(f=0;f<a.length-1;f++){var g=a[f];g in d||(d[g]={});d=d[g]}a=a[a.length-1];f=d[a];e=e(f);e!=f&&null!=e&&$jscomp.defineProperty(d,a,{configurable:!0,writable:!0,value:e})}};$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6","es3");
var plgGdprAllCookiesDisabledByScript=!1,plgGdprObserverMutationTags=null,plgGdprCustomScriptExecutionGeneric=!1,detectedOldIPhone=!1;if(null!==navigator.userAgent.match(/iPhone/i)){var iphone4=480==window.screen.height,iphone5=568==window.screen.height;if(iphone4||iphone5)detectedOldIPhone=!0}
var plgGdprDisableAllCookies=function(a){var e=document.cookie.split("; "),d=["cookieconsent_status"];"undefined"!==typeof gdprJSessCook&&d.push(gdprJSessCook);"undefined"!==typeof gdprJAdminSessCook&&d.push(gdprJAdminSessCook);if(gdprConfigurationOptions.allowedCookies){var f=gdprConfigurationOptions.allowedCookies.split(",");d=d.concat(f)}f=function(a){for(var b=window.location.hostname.split(".");0<b.length;){var m=encodeURIComponent(a.split(";")[0].split("=")[0])+"=; expires=Thu, 01-Jan-1970 00:00:01 GMT; domain="+
b.join(".")+" ;path=",c=location.pathname.split("/");for(document.cookie=m+"/";0<c.length;){var d=c.join("/");d||(d="/");document.cookie=m+d;c.pop()}b.shift()}};for(var g=0;g<e.length;g++){for(var b=!0,c=0;c<d.length;c++)-1!=e[g].indexOf(d[c])&&(b=!1);b&&f(e[g])}a||!gdprConfigurationOptions.blockCookieDefine||detectedOldIPhone||Object.defineProperty(document,"cookie",{get:function(){return""},set:function(){return!0}});a=gdprConfigurationOptions.externalAdvancedBlockingModeCustomAttribute?",["+gdprConfigurationOptions.externalAdvancedBlockingModeCustomAttribute+
"*=gdprlock]":"";gdprConfigurationOptions.placeholderBlockedResources?jQuery("*[src*=gdprlock],*[data-source=gdprlock]"+a).filter(function(a,b){return"script"==b.nodeName.toLowerCase()||"link"==b.nodeName.toLowerCase()?!1:!0}).replaceWith(function(a){var b="";gdprConfigurationOptions.placeholderOnpageUnlock&&(a=this.attributes,"undefined"!==typeof a["data-original-src"]&&jQuery.each(a,function(a,c){"data-original-src"==c.name&&(b+=" "+c.name+'="'+c.value+'"');-1==c.name.indexOf("data")&&(b+=" data-original-"+
c.name+'="'+c.value+'"')}));return'<div class="gdprlock-placeholder"'+b+'><div class="gdprlock-placeholder-text">'+gdprConfigurationOptions.placeholderBlockedResourcesText+"</div></div>"}):jQuery("*[src*=gdprlock],*[data-source=gdprlock]"+a).remove();plgGdprAllCookiesDisabledByScript=!0},plgGdprShowReloadWindow=function(){gdprConfigurationOptions.showReloadMsg&&(jQuery("#gdpr_reload_msg").remove(),jQuery("<div/>").attr("id","gdpr_reload_msg").prependTo("body").append('<div id="gdpr_reload_msgtext"><span id="gdpr_reload_info_icon">&#x24D8;</span>'+
gdprConfigurationOptions.showReloadMsgText+"</div>").css("margin-top",0).hide().fadeIn(500).delay(2500).fadeOut(500,function(){jQuery(this).remove()}));window.location.reload()};
if(gdprConfigurationOptions.autoDetectYoutubePoster){var getYouTubePoster=function(a,e){(e=function(a){return(a=a.match(/(?:https?:\/\/)?(?:www\.)?(?:youtube\.com\/(?:[^\/\n\s]+\/\S+\/|(?:v|e(?:mbed)?)\/|\S*?[?&]v=)|youtu\.be\/)([a-zA-Z0-9_-]{11})/))?a[1]:null}(e))&&fetch("https://www.googleapis.com/youtube/v3/videos?id="+e+"&key="+gdprConfigurationOptions.autoDetectYoutubePosterApikey+"&part=snippet").then(function(a){return a.json()}).then(function(d){d=d.items[0].snippet.thumbnails.maxres.url;
jQuery(a).css({background:"url("+d+") no-repeat","background-size":"contain"})}).catch(function(a){})};setTimeout(function(){jQuery('div.gdprlock-placeholder[data-original-src*="youtube"],div.gdprcookielock-placeholder[data-original-src*="youtube"]').each(function(a,e){a=jQuery(e).data("original-src");getYouTubePoster(e,a)})},1)}
var plgGdprCssEscape=function(a){var e=String(a),d=e.length,f=-1,g="",b=e.charCodeAt(0);if(48<=b&&57>=b)return a;for(;++f<d;)a=e.charCodeAt(f),g=0==a?g+"\ufffd":1<=a&&31>=a||127==a||0==f&&48<=a&&57>=a||1==f&&48<=a&&57>=a&&45==b?g+("\\"+a.toString(16)+" "):0==f&&1==d&&45==a?g+("\\"+e.charAt(f)):128<=a||45==a||95==a||48<=a&&57>=a||65<=a&&90>=a||97<=a&&122>=a?g+e.charAt(f):g+("\\"+e.charAt(f));return g};
(function(){if("undefined"!==typeof gdpr_unset_categories_cookies)for(var a=0;a<gdpr_unset_categories_cookies.length;a++)for(var e=gdpr_unset_categories_cookies[a],d=window.location.hostname.split(".");0<d.length;){var f=encodeURIComponent(e.split(";")[0].split("=")[0])+"=; expires=Thu, 01-Jan-1970 00:00:01 GMT; domain="+d.join(".")+" ;path=",g=location.pathname.split("/");for(document.cookie=f+"/";0<g.length;){var b=g.join("/");b||(b="/");document.cookie=f+b;g.pop()}d.shift();gdprConfigurationOptions.blockLocalStorage&&
localStorage.removeItem(e);gdprConfigurationOptions.blockSessionStorage&&sessionStorage.removeItem(e)}})();gdprConfigurationOptions.lawByCountry||("opt-in"!=gdprConfigurationOptions.complianceType||localStorage.getItem("hasConsented")||localStorage.getItem("setConsentedCookie")||plgGdprDisableAllCookies(),"opt-out"==gdprConfigurationOptions.complianceType&&localStorage.getItem("hasDeclined")&&plgGdprDisableAllCookies());
gdprConfigurationOptions.optoutIndividualResources&&function(){var a=localStorage.getItem("gdprCookiesChoices");a&&(a=JSON.parse(a));a&&function(){for(var d=document.cookie.split("; "),b=0;b<d.length;b++){var c=!1,m=encodeURIComponent(d[b].split(";")[0].split("=")[0]);m in a&&(c=!0);if(c){c=d[b];for(var h=window.location.hostname.split(".");0<h.length;){var k=encodeURIComponent(c.split(";")[0].split("=")[0])+"=; expires=Thu, 01-Jan-1970 00:00:01 GMT; domain="+h.join(".")+" ;path=",e=location.pathname.split("/");
for(document.cookie=k+"/";0<e.length;){var f=e.join("/");f||(f="/");document.cookie=k+f;e.pop()}h.shift()}gdprConfigurationOptions.blockLocalStorage&&localStorage.removeItem(m);gdprConfigurationOptions.blockSessionStorage&&sessionStorage.removeItem(m)}}}();if(a){var e=[],d=gdprConfigurationOptions.externalAdvancedBlockingModeTags.toLowerCase().split(","),f=function(e){var b=!1,c=e.nodeName.toLowerCase();if(-1==jQuery.inArray(c,d))return b;jQuery.each(a,function(c){if(!a[c]&&-1<e.outerHTML.indexOf(c)&&
-1==e.outerHTML.indexOf("gdpr"))return b=c,!0});return b};plgGdprObserverMutationTags=new MutationObserver(function(a){for(var b=0;b<a.length;b++)for(var c=a[b].addedNodes,m=0;m<c.length;m++){var h=c[m],d=h.nodeName.toLowerCase();-1==jQuery.inArray(d,e)&&e.push(d);if(1===h.nodeType&&(d=f(h))){var l=function(a){"script"===h.nodeName&&a.preventDefault();h.removeEventListener("beforescriptexecute",l)};h.addEventListener("beforescriptexecute",l);if(gdprConfigurationOptions.placeholderBlockedResources&&
"script"!=h.nodeName.toLowerCase()&&"link"!=h.nodeName.toLowerCase()){var g=gdprConfigurationOptions.placeholderIndividualBlockedResourcesAction?"gdprlock-placeholder ":"",p="";gdprConfigurationOptions.placeholderOnpageUnlock&&"iframe"==h.nodeName.toLowerCase()&&jQuery.each(h.attributes,function(a,b){p+=" data-original-"+b.name+'="'+b.value+'"'});jQuery(h).replaceWith('<div class="'+g+'gdprcookielock-placeholder"'+p+'><div class="gdprcookielock-placeholder-text">'+gdprConfigurationOptions.placeholderIndividualBlockedResourcesText.replace("{domain}",
d)+"</div></div>")}else jQuery(h).remove()}}});plgGdprObserverMutationTags.observe(document.documentElement,{childList:!0,subtree:!0});setTimeout(function(){jQuery.each(d,function(d,b){-1==jQuery.inArray(b,e)&&jQuery.each(a,function(c){if(!a[c]){var d=jQuery(b+'[src*="'+c+'"], '+b+'[href*="'+c+'"], '+b+'[poster*="'+c+'"]');if(gdprConfigurationOptions.placeholderBlockedResources&&"script"!=b&&"link"!=b){var h=gdprConfigurationOptions.placeholderIndividualBlockedResourcesAction?"gdprlock-placeholder ":
"";d.replaceWith(function(a){var d="";gdprConfigurationOptions.placeholderOnpageUnlock&&"iframe"==b&&jQuery.each(this.attributes,function(a,b){d+=" data-original-"+b.name+'="'+b.value+'"'});return'<div class="'+h+'gdprcookielock-placeholder"'+d+'><div class="gdprcookielock-placeholder-text">'+gdprConfigurationOptions.placeholderIndividualBlockedResourcesText.replace("{domain}",c)+"</div></div>"})}else d.remove()}})})},500)}a&&(d=gdprConfigurationOptions.externalAdvancedBlockingModeTags.toLowerCase().split(","),
jQuery.each(a,function(e){if(!a[e]){var b=plgGdprCssEscape(e),c=gdprConfigurationOptions.externalAdvancedBlockingModeCustomAttribute?",["+gdprConfigurationOptions.externalAdvancedBlockingModeCustomAttribute+"*="+b+"]":"";jQuery.each(d,function(a,d){jQuery(d+"[src*="+b+"],"+d+"[href*="+b+"]"+c).each(function(a,b){if(gdprConfigurationOptions.placeholderBlockedResources&&"script"!=b.nodeName.toLowerCase()&&"link"!=b.nodeName.toLowerCase()){a=gdprConfigurationOptions.placeholderIndividualBlockedResourcesAction?
"gdprlock-placeholder ":"";var c="";gdprConfigurationOptions.placeholderOnpageUnlock&&"iframe"==b.nodeName.toLowerCase()&&jQuery.each(this.attributes,function(a,b){c+=" data-original-"+b.name+'="'+b.value+'"'});jQuery(b).replaceWith('<div class="'+a+'gdprcookielock-placeholder"'+c+'><div class="gdprcookielock-placeholder-text">'+gdprConfigurationOptions.placeholderIndividualBlockedResourcesText.replace("{domain}",e)+"</div></div>")}else jQuery(b).remove()})})}}))}();
jQuery(function(a){if(!plgGdprAllCookiesDisabledByScript){var e=gdprConfigurationOptions.externalAdvancedBlockingModeCustomAttribute?",["+gdprConfigurationOptions.externalAdvancedBlockingModeCustomAttribute+"*=gdprlock]":"";gdprConfigurationOptions.placeholderBlockedResources?a("*[src*=gdprlock],*[data-source=gdprlock]"+e).filter(function(a,c){return"script"==c.nodeName.toLowerCase()||"link"==c.nodeName.toLowerCase()?!1:!0}).replaceWith(function(b){var c="";gdprConfigurationOptions.placeholderOnpageUnlock&&
(b=this.attributes,"undefined"!==typeof b["data-original-src"]&&a.each(b,function(a,b){"data-original-src"==b.name&&(c+=" "+b.name+'="'+b.value+'"');-1==b.name.indexOf("data")&&(c+=" data-original-"+b.name+'="'+b.value+'"')}));return"undefined"===typeof this.dataset.gdprDomain?'<div class="gdprlock-placeholder"'+c+'><div class="gdprlock-placeholder-text">'+gdprConfigurationOptions.placeholderBlockedResourcesText+"</div></div>":'<div class="'+(gdprConfigurationOptions.placeholderIndividualBlockedResourcesAction?
"gdprlock-placeholder ":"")+'gdprcookielock-placeholder"'+c+'><div class="gdprcookielock-placeholder-text">'+gdprConfigurationOptions.placeholderIndividualBlockedResourcesText.replace("{domain}",this.dataset.gdprDomain)+"</div></div>"}):jQuery("*[src*=gdprlock],*[data-source=gdprlock]"+e).remove()}window.gdprIsCookieConsentPresent=function(a){a=("; "+document.cookie).split("; "+a+"=");return 2!=a.length?void 0:a.pop().split(";").shift()}("cookieconsent_status");var d=function(){var b=a("iframe").length,
c=!!navigator.mozGetUserMedia;gdprConfigurationOptions.blockExternalCookiesDomains&&b&&c&&localStorage.setItem("refreshIframeCache",!0);if(gdpr_enable_log_cookie_consent){if("opt-in"==gdprConfigurationOptions.complianceType)var d=localStorage.getItem("hasConsented");else"opt-out"==gdprConfigurationOptions.complianceType&&(d=!localStorage.getItem("hasDeclined"));a.ajax({type:"POST",url:gdpr_ajax_livesite+"index.php?option=com_gdpr&task=user.processGenericCookieCategories",data:{gdpr_generic_cookie_consent:d?
1:0}}).then(function(){plgGdprShowReloadWindow()})}else setTimeout(function(){plgGdprShowReloadWindow()},0)},f=function(){plgGdprObserverMutationTags&&plgGdprObserverMutationTags.disconnect();a.ajax({type:"POST",dataType:"json",url:gdpr_ajax_livesite+"index.php?option=com_gdpr&task=user.getDomainsSum",data:{noredirect:1}}).then(function(b){b=Object.keys(b).map(function(a){return b[a]});var c=localStorage.getItem("gdprCookiesChoices");c&&(c=JSON.parse(c),a.each(c,function(a){c[a]||b.push(a)}));a("div.gdprlock-placeholder[data-original-src],div.gdprcookielock-placeholder[data-original-src]").replaceWith(function(c){var d=
"";c=this.attributes;if("undefined"!==typeof c["data-original-src"]){for(var e in b)if(-1<c["data-original-src"].value.indexOf(b[e]))return this;a.each(c,function(a,b){0==b.name.indexOf("data-original-")&&(d+=b.name.replace("data-original-","")+'="'+b.value+'" ')});return"<iframe "+d+"></iframe>"}});a.each(b,function(b,c){b=plgGdprCssEscape(c);a("iframe[src*="+b+"]").each(function(b,d){b=gdprConfigurationOptions.placeholderIndividualBlockedResourcesAction?"gdprlock-placeholder ":"";var e="";a.each(this.attributes,
function(a,b){e+=" data-original-"+b.name+'="'+b.value+'"'});a(d).replaceWith('<div class="'+b+'gdprcookielock-placeholder"'+e+'><div class="gdprcookielock-placeholder-text">'+gdprConfigurationOptions.placeholderIndividualBlockedResourcesText.replace("{domain}",c)+"</div></div>")})});gdprConfigurationOptions.autoDetectYoutubePoster&&a('div.gdprlock-placeholder[data-original-src*="youtube"],div.gdprcookielock-placeholder[data-original-src*="youtube"]').each(function(b,c){b=a(c).data("original-src");
getYouTubePoster(c,b)})})},g=function(){plgGdprObserverMutationTags&&plgGdprObserverMutationTags.disconnect();a.ajax({type:"POST",dataType:"json",url:gdpr_ajax_livesite+"index.php?option=com_gdpr&task=user.getDomainsSum",data:{noredirect:1}}).then(function(b){b=Object.keys(b).map(function(a){return b[a]});var c=localStorage.getItem("gdprCookiesChoices");c&&(c=JSON.parse(c),a.each(c,function(a){c[a]||b.push(a)}));a("script[data-gdprlock-original-script-src]").replaceWith(function(c){c=this.attributes;
if("undefined"!==typeof c["data-gdprlock-original-script-src"]){for(var d in b)if(-1<c["data-gdprlock-original-script-src"].value.indexOf(b[d]))return this;a.getScript(c["data-gdprlock-original-script-src"].value);a(this).attr("src",c["data-gdprlock-original-script-src"].value).removeAttr("data-gdprlock-original-script-src").removeAttr("data-source");return this}});a.each(b,function(b,c){b=plgGdprCssEscape(c);a("script[src*="+b+"]").each(function(b,c){b=a(c).attr("src");a(c).attr("data-gdprlock-original-script-src",
b).attr("data-source","gdprlock");a(c).removeAttr("src")})})})};a(document).on("click","a.cc-allow",function(b){"opt-out"==gdprConfigurationOptions.complianceType&&localStorage.getItem("hasDeclined")&&(localStorage.removeItem("hasDeclined"),localStorage.removeItem("hasDenyMessage"),localStorage.removeItem("hasExplititDeclinedAll"),localStorage.setItem("setAllowRevokedCookie",!0),d());gdpr_enable_log_cookie_consent&&"opt-out"==gdprConfigurationOptions.complianceType&&!localStorage.getItem("hasFirstDeclined")&&
a.ajax({type:"POST",url:gdpr_ajax_livesite+"index.php?option=com_gdpr&task=user.processGenericCookieCategories",data:{gdpr_generic_cookie_consent:1}})});localStorage.getItem("refreshIframeCache")&&(a("iframe").each(function(b,c){b=a(c).clone();a(c).after(b).remove()}),localStorage.getItem("setConsentedCookie")||localStorage.removeItem("refreshIframeCache"));window.cookieconsent.initialise({type:gdprConfigurationOptions.complianceType,layout:gdprConfigurationOptions.toolbarLayout,theme:gdprConfigurationOptions.toolbarTheme,
centertheme:gdprConfigurationOptions.toolbarCenterTheme,position:gdprConfigurationOptions.toolbarPosition,revokeposition:gdprConfigurationOptions.revokePosition,container:document.querySelector(gdprConfigurationOptions.containerSelector),palette:{popup:{background:gdprConfigurationOptions.popupBackground,text:gdprConfigurationOptions.popupText,link:gdprConfigurationOptions.popupLink,effect:gdprConfigurationOptions.popupEffect},button:{background:gdprConfigurationOptions.buttonBackground,border:gdprConfigurationOptions.buttonBorder,
text:gdprConfigurationOptions.buttonText},highlight:{background:gdprConfigurationOptions.highlightBackground,border:gdprConfigurationOptions.highlightBorder,text:gdprConfigurationOptions.highlightText},highlightDismiss:{background:gdprConfigurationOptions.highlightDismissBackground,border:gdprConfigurationOptions.highlightDismissBorder,text:gdprConfigurationOptions.highlightDismissText},highlightOpacity:{opacity:gdprConfigurationOptions.highlightOpacity},buttonall:{background:gdprConfigurationOptions.allowallButtonBackground,
border:gdprConfigurationOptions.allowallButtonBorder,text:gdprConfigurationOptions.allowallButtonText},buttonSettings:{background:gdprConfigurationOptions.toggleCookieSettingsButtonBackground,border:gdprConfigurationOptions.toggleCookieSettingsButtonBorder,text:gdprConfigurationOptions.toggleCookieSettingsButtonText}},revokable:!!gdprConfigurationOptions.revokable,location:!!gdprConfigurationOptions.lawByCountry,law:{regionalLaw:!gdprConfigurationOptions.lawByCountry},showLink:!!gdprConfigurationOptions.showLinks,
static:!gdprConfigurationOptions.toolbarPositionmentType,dismissOnScroll:gdprConfigurationOptions.dismissOnScroll,dismissOnTimeout:gdprConfigurationOptions.dismissOnTimeout,animateRevokable:!!gdprConfigurationOptions.hideRevokableButton,onInitialise:function(a){"opt-out"==gdprConfigurationOptions.complianceType&&localStorage.getItem("setAllowRevokedCookie")&&(this.setStatus("allow",!0),localStorage.removeItem("setAllowRevokedCookie"),d())},content:{header:gdprConfigurationOptions.headerText,message:gdprConfigurationOptions.messageText,
dismiss:gdprConfigurationOptions.dismissText,allow:gdprConfigurationOptions.allowText,deny:gdprConfigurationOptions.denyText,allowall:gdprConfigurationOptions.allowallText,link:gdprConfigurationOptions.cookiePolicyLinkText,href:gdprConfigurationOptions.cookiePolicyLink,privacylink:gdprConfigurationOptions.privacyPolicyLinkText,privacyhref:gdprConfigurationOptions.privacyPolicyLink},onStatusChange:function(b,c){c=this.options.type;var e=this.hasConsented();if("opt-in"==c&&(e||a("a.cc-btn",this.element).hasClass("cc-allow"))&&
"allow"==b){var h=localStorage.getItem("hasConsented"),k=localStorage.getItem("hasExplititDeclinedAll"),l={hasConsented:!0,timestamp:(new Date).getTime()};localStorage.setItem("hasConsented",JSON.stringify(l));plgGdprAllCookiesDisabledByScript&&("hard"==gdprConfigurationOptions.declineButtonBehavior||gdprConfigurationOptions.blockCookieDefine&&"soft"==gdprConfigurationOptions.declineButtonBehavior)&&localStorage.setItem("setConsentedCookie",!0);localStorage.removeItem("hasExplititDeclinedAll");gdprConfigurationOptions.preserveLockedCategories?
a("input.cc-cookie-checkbox:not([readonly])").attr("disabled",!1):a("input.cc-cookie-checkbox").attr("disabled",!1);if(gdprConfigurationOptions.disableFirstReload){l=!1;var r=parseInt(localStorage.getItem("autoActivateOnNextPage")),p=!localStorage.getItem("hasFirstAccepted");if(!p||1==r||k)h&&gdprIsCookieConsentPresent||(l=!0,d());gdpr_enable_log_cookie_consent&&p&&!l&&a.ajax({type:"POST",url:gdpr_ajax_livesite+"index.php?option=com_gdpr&task=user.processGenericCookieCategories",data:{gdpr_generic_cookie_consent:1}});
p&&(l={hasFirstAccepted:!0,timestamp:(new Date).getTime()},localStorage.setItem("hasFirstAccepted",JSON.stringify(l)));"center"==gdprConfigurationOptions.toolbarPosition&&gdprConfigurationOptions.positionCenterBlurEffect&&p&&a("body").css({filter:"none","pointer-events":"all"})}else h&&gdprIsCookieConsentPresent||d();if("soft"==gdprConfigurationOptions.declineButtonBehavior&&!gdprConfigurationOptions.preserveLockedCategories){var n=1;"slow"==gdprConfigurationOptions.allowallButtonTimingAjax&&(n=2);
"extrafast"==gdprConfigurationOptions.allowallButtonTimingAjax&&(n=.5);for(k=1;4>=k;k++)setTimeout(function(b){a("input[id=cookie_cat"+b+"][readonly]:not(:checked)").trigger("click").prop("checked",!0)},400*k*n,k)}gdprConfigurationOptions.placeholderOnpageUnlock&&setTimeout(function(){f()},250);gdprConfigurationOptions.scriptsOnpageUnlock&&setTimeout(function(){g()},500);gdprConfigurationOptions.enableCustomScriptExecGeneric&&!plgGdprCustomScriptExecutionGeneric&&(h=document.createElement("script"),
h.innerHTML=gdprConfigurationOptions.customScriptExecGeneric,document.head.appendChild(h),plgGdprCustomScriptExecutionGeneric=!0)}if("opt-in"==c&&(!e||a("a.cc-btn",this.element).hasClass("cc-deny"))&&"deny"==b){h=localStorage.getItem("hasConsented");localStorage.removeItem("hasConsented");localStorage.removeItem("setConsentedCookie");l={hasDeclined:!0,timestamp:(new Date).getTime()};localStorage.setItem("hasFirstDeclined",JSON.stringify(l));localStorage.setItem("hasExplititDeclinedAll",JSON.stringify(l));
if("hard"==gdprConfigurationOptions.declineButtonBehavior)if(this.setStatus("deny",!0),gdprConfigurationOptions.preserveLockedCategories){if(a("input.cc-cookie-checkbox:not([readonly])").attr("disabled",!0).prop("checked",!1),a("div.cc-checkboxes-container input.cc-cookie-checkbox:not([readonly]):checked + span").addClass("cc-checkbox-switcher-category-transitioning"),k=!!jQuery("div.gdpr-component-view").length||!1)k=a("input.cc-cookie-checkbox:not([readonly])").parents("div.gdpr-component-view"),
a("div.gdpr_cookie_switcher",k).addClass("inactive")}else a("input.cc-cookie-checkbox").attr("disabled",!0).prop("checked",!1),a("div.cc-checkboxes-container input.cc-cookie-checkbox:checked + span").addClass("cc-checkbox-switcher-category-transitioning"),(k=!!jQuery("div.gdpr-component-view").length||!1)&&a("div.gdpr_cookie_switcher").addClass("inactive");else if(this.setStatus("allow",!0),localStorage.removeItem("hasExplititDeclinedAll"),localStorage.removeItem("hasFirstAccepted"),n=1,"slow"==gdprConfigurationOptions.allowallButtonTimingAjax&&
(n=2),"extrafast"==gdprConfigurationOptions.allowallButtonTimingAjax&&(n=.5),gdprConfigurationOptions.preserveLockedCategories){for(k=1;4>=k;k++)setTimeout(function(b){a("input[id=cookie_cat"+b+"]:checked:not([readonly])").trigger("click").prop("checked",!1)},400*k*n,k);if(k=!!jQuery("div.gdpr-component-view").length||!1)k=a("input.cc-cookie-checkbox:not([readonly])").parents("div.gdpr-component-view"),a("div.gdpr_cookie_switcher",k).addClass("inactive")}else{for(k=1;4>=k;k++)setTimeout(function(b){a("input[id=cookie_cat"+
b+"]:checked").trigger("click").prop("checked",!1)},400*k*n,k);(k=!!jQuery("div.gdpr-component-view").length||!1)&&a("div.gdpr_cookie_switcher").addClass("inactive")}if(h)"hard"==gdprConfigurationOptions.declineButtonBehavior?d():setTimeout(function(){gdprConfigurationOptions.alwaysReloadAfterCategoriesChange&&window.cookieconsent.cookieCategoriesHasChanged?d():gdpr_enable_log_cookie_consent&&a.ajax({type:"POST",url:gdpr_ajax_livesite+"index.php?option=com_gdpr&task=user.processGenericCookieCategories",
data:{gdpr_generic_cookie_consent:0}});gdprConfigurationOptions.placeholderOnpageUnlock&&setTimeout(function(){f()},250);gdprConfigurationOptions.scriptsOnpageUnlock&&setTimeout(function(){g()},500)},2E3*n);else{var q=function(){gdprConfigurationOptions.autoRedirectOnDecline&&gdprConfigurationOptions.autoRedirectOnDeclineLink&&(window.location.href=gdprConfigurationOptions.autoRedirectOnDeclineLink);gdprConfigurationOptions.reloadOnfirstDeclineall&&"undefined"!==typeof gdprUseCookieCategories&&plgGdprShowReloadWindow()};
gdpr_enable_log_cookie_consent?"hard"==gdprConfigurationOptions.declineButtonBehavior?a.ajax({type:"POST",url:gdpr_ajax_livesite+"index.php?option=com_gdpr&task=user.processGenericCookieCategories",data:{gdpr_generic_cookie_consent:0}}).then(function(){q()}):setTimeout(function(){a.ajax({type:"POST",url:gdpr_ajax_livesite+"index.php?option=com_gdpr&task=user.processGenericCookieCategories",data:{gdpr_generic_cookie_consent:0}}).then(function(){q()})},2E3*n):q()}}if("opt-out"==c&&!e&&!localStorage.getItem("hasDeclined")){plgGdprDisableAllCookies(!0);
l={hasDeclined:!0,timestamp:(new Date).getTime()};if(gdprConfigurationOptions.autoRedirectOnDecline&&gdprConfigurationOptions.autoRedirectOnDeclineLink&&!localStorage.getItem("hasFirstDeclined")){window.location.href=gdprConfigurationOptions.autoRedirectOnDeclineLink;return}localStorage.setItem("hasDeclined",JSON.stringify(l));localStorage.setItem("hasFirstDeclined",JSON.stringify(l));localStorage.setItem("hasExplititDeclinedAll",JSON.stringify(l));gdprConfigurationOptions.preserveLockedCategories?
a("input.cc-cookie-checkbox:not([readonly])").attr("disabled",!0):a("input.cc-cookie-checkbox").attr("disabled",!0);d()}"opt-out"==c&&(e||a("a.cc-btn",this.element).hasClass("cc-allow"))&&"allow"==b&&(gdprConfigurationOptions.placeholderOnpageUnlock&&setTimeout(function(){f()},250),gdprConfigurationOptions.scriptsOnpageUnlock&&setTimeout(function(){g()},500),gdprConfigurationOptions.enableCustomScriptExecGeneric&&!plgGdprCustomScriptExecutionGeneric&&(h=document.createElement("script"),h.innerHTML=
gdprConfigurationOptions.customScriptExecGeneric,document.head.appendChild(h),plgGdprCustomScriptExecutionGeneric=!0));gdprConfigurationOptions.denyMessageEnabled&&"allow"==b&&localStorage.removeItem("hasDenyMessage")},onPopupOpen:function(b){"opt-in"!=gdprConfigurationOptions.complianceType&&"opt-out"!=gdprConfigurationOptions.complianceType||!gdprConfigurationOptions.autoAcceptOnNextPage||b||localStorage.getItem("hasExplititDeclinedAll")||(b=localStorage.getItem("autoActivateOnNextPage"),2==parseInt(b)?
(localStorage.setItem("autoActivateOnNextPage",1),"opt-in"==gdprConfigurationOptions.complianceType?(a("div.cc-window.cc-banner,div.cc-window.cc-floating").hide(),a("a.cc-btn.cc-allow").trigger("click")):"opt-out"==gdprConfigurationOptions.complianceType&&setTimeout(function(){a("a.cc-btn.cc-allow").trigger("click")},100)):b||localStorage.setItem("autoActivateOnNextPage",2))}});if(gdprConfigurationOptions.trackExistingCheckboxSelectors)a(gdprConfigurationOptions.trackExistingCheckboxSelectors).on("change",
function(b){parentForm=a(b.target).parents("form");var c={url:a(location).attr("href"),formid:parentForm.attr("id"),formname:parentForm.attr("name"),formfields:{}};b=a(this);var d=b.attr("type"),e=parseInt(b.val());"checkbox"==d&&0===e&&b.val(1);a(this).is(":checked")&&0!=parseInt(a(this).val())?(b=gdprConfigurationOptions.trackExistingCheckboxConsentLogsFormfields.split(","),b=b.map(function(a,b){return a.trim()}),a.each(b,function(b,d){b=a("input[name*="+d+"]:not(:hidden), input[id*="+d+"]:not(:hidden), textarea[name*="+
d+"], textarea[id*="+d+"]",parentForm);b.length&&a.each(b,function(b,d){(b=a(d).attr("id"))||(b=a(d).attr("name"));b=b.replace(/[-_]/gi," ");b=b.replace(/[\[\]]/gi,"");b=b.replace("jform","");b=b.trim();d=a(d).val();c.formfields[b]=d})}),a.ajax({type:"POST",url:gdpr_ajax_livesite+"index.php?option=com_gdpr&task=user.storeConsent&format=raw",data:c})):a.ajax({type:"POST",url:gdpr_ajax_livesite+"index.php?option=com_gdpr&task=user.deleteConsent&format=raw",data:c})})});